### ISSUE TITLE
[BT] Executing /regenerate( or delete )allbattletowers hangs internal server

### ISSUE THREAD

**Issue by Revvilo** [AtomicStryker/atomicstrykers-minecraft-mods#112]
Running /regenerateallbattletowers or /deleteallbattletowers seems to halt the internal server and prints the following error to the console;
https://pastebin.com/wLxLQ2bC

**Comment by AtomicStryker** [comment]
OK what is happening there is Battletowers deadlocking itself because another mod (line com.amadornes.rscircuits.block.BlockBUD.onBlockUpdate(BlockBUD.java:103)) causes new World Generation during the Block Update during the Block Deletion of the Battletower delete command.

Despite the "cause" being another mod, Battletowers should be more robust here. I'll see what i can do.

**Comment by AtomicStryker** [comment]
You didn't specify which version of MC this was for, i will fix the bug for 1.11.2 and 1.10.2
And done
Enjoy and thanks for bringing it up

**Comment by Revvilo** [comment]
Brilliant man, I will update ASAP, and yea sorry I was using 1.10.2. I'll do my best to remember to specify that in future posts. :D
Strange how Super Circuit Maker is causing that, I've never placed a BUD Detector at all...
