### ISSUE TITLE
Incompatibility with Furnus Mod

### ISSUE THREAD

**Issue by kreezxil** [AtomicStryker/atomicstrykers-minecraft-mods#114]
Furnus 1.11.2-1.93
Limelib 1.11.2-1.5.4
Multi Mine 1.11.2 

When this combinate of mods exist, breaking/harvesting a machine from Furnus mod which depends on limelib duplicates the block drop in the world. Removing multimine solves this issue.

See https://github.com/MrRiegel/Furnus/issues/20 where I practically tortured MrRiegel. Sorry MrRiegel.

**Comment by AtomicStryker** [comment]
That's what the block blacklist in Multi Mine is for

**Comment by kreezxil** [comment]
But why does the other mod dupe tho? Other mods with custom tile entities
don't do this in my pack.

**Comment by AtomicStryker** [comment]
It's because of that mods specific implementation of dropping the block - it is doing so in a different place than Multi Mine expects, so when Multi Mine "pops" the block and drops it, the mod itself also drops it. *Most* mods drop the block in such a way that Multi Mine can replace it seamlessly. It isn't "wrong" just incompatible with Multi Mine as it is.
