### ISSUE TITLE
Dynamic Lighting in forge 1.12 - Light not rendering

### ISSUE THREAD

**Issue by sebasjham** [AtomicStryker/atomicstrykers-minecraft-mods#118]
I cannot figure if I'm doing something wrong as the mods show up in the menus and I can turn global lights on and off.  All the modules are loaded, however, are there additional steps to enable them that I do not know of? Here's a look at my situation in eclipse:

![screen](https://user-images.githubusercontent.com/20546772/27203847-c210d6d0-51f5-11e7-9086-34ddd137e285.png)

**Comment by AtomicStryker** [comment]
Yes the coremod isn't triggered like I said.

**Comment by sebasjham** [comment]
sorry for wasting your time

**Comment by AtomicStryker** [comment]
The "like i said" was somewhere else, either via comments or PM somewhere, i'll repeat it here for posteriority: To get coremods working in forge/mcp environments, there needs to be a "fake" mod jar in the runtime/mods/ folder which contains the META-INF part of the actual mod. Otherwise, transformers won't run and, in this instance Dynamic Lights will simply not work.
