### ISSUE TITLE
Choke enchantment rarely left player's hunger bar covered with bubbles

### ISSUE THREAD

**Issue by DBotThePony** [AtomicStryker/atomicstrykers-minecraft-mods#162]
![very bad](https://i.dbot.serealia.ca/2017/12/a0da886863_javaw_2017-12-10_11-58-13.png)

Mostly happens when:
* Player runs away from mob without attacking the mob
* Mob friendly-fires enchanted mob **before** taking any damage from player
* Mob 'ninjas' into blocks and dies there
* Mob despawns while targeting a player (minecraft...)
* Mob is killed by another player, while targeting local player *(bug appears very rarely in this situation)*

Finding another mob with `Choke` and killing it fixes the issue, but only if mob was killed not by conditions above

**Comment by AtomicStryker** [comment]
The problem is that a modifiers target may change or it may not receive update ticks to "reset" a player entitiy from a modded state. I have implemented a timer that keeps track of modified players and calls a reset for each modifier when they stopped messing with him:

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/85ae6ae40a5c2f220734211f673f40f8eaef9f53

I won't be able to test this myself. See if this helps, if you can. Also, the fix is only for 1.12.2

**Comment by AtomicStryker** [comment]
And thank you, for reporting it

**Comment by DBotThePony** [comment]
Going to test

**Comment by DBotThePony** [comment]
Fix seems to work.

Also, https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/160 - Your closest license is MIT (i use Apache 2.0 for my gmod addons).
