### ISSUE TITLE
[Battletowers] Guardian's behaviors

### ISSUE THREAD

**Issue by Lion4K** [AtomicStryker/atomicstrykers-minecraft-mods#183]
I have observed this bugs in some versions now, that doesn't used to happen before, and decided to share them here.

First: Guardian is blocking access to chests not on his level.
He being able to block the chests or or sometimes 2 levels before his.

Second: Guardian is destroying the chests  himself and wasting the goodies (with his fireball attack) before the player can even get to last level.

That's all.

**Comment by AtomicStryker** [comment]
When i first implemented the chest lock, i realized i had set the distance too high and it locked chests below the roof with the golem on it. Which then woke up, smashed through the roof and stomped the player.

I absolutely loved it, and thus it is not and has never been a bug. There's literally a scene with this happening in the Promo video. That thing is ANCIENT.

The second has been in the mod since i added fireballs to the golem, which was the very first version. Your information is wrong good sir.

**Comment by Lion4K** [comment]
oh, if you say so. OK.

Thanks!
