### ISSUE TITLE
[Ruins] enableStick=0 doesn't work

### ISSUE THREAD

**Issue by Insane96** [AtomicStryker/atomicstrykers-minecraft-mods#201]
Tried adding it but still spams chat with block's data.
![asdasd](https://user-images.githubusercontent.com/7185104/40273043-2e52ba5c-5bb9-11e8-9102-cbc29c24308e.png)

**Comment by AtomicStryker** [comment]
That is not a helpful bug report at all.

- which version of minecraft
- which version of the Ruins mod
- where did you add enableStick=0 and when

**Comment by AtomicStryker** [comment]
Try this jar https://github.com/AtomicStryker/github.io/blob/master/files/1.12.1/Ruins-1.12.1.jar

**Comment by QuarterAnimal** [comment]
Two things to note. First--albeit least important--the **enableStick** parameter only takes a value of **true** or **false**, so **0** isn't valid. Now, it just so happens the way Java parses boolean values, anything that isn't **true** is interpreted as **false**, including **0**....which happens to be your intent, anyway. I'm only mentioning it here because if you ever try to set it to **1**, you won't get the result you want, since that's also equivalent to **false**.

The **enableStick** parameter was added around mid-January of this year, so you need to be using a version of Ruins later than that to affect it. It's not possible to know which version you're using with what you provided, though I can tell the **config/ruins.txt** configuration file was created by an earlier version. That's not necessarily a problem, but if you updated Ruins for an _already-existing_ world, you need to know all the dimensions have their own copies of ruins.txt--those are the ones actually applied. The file in the config folder is only copied to dimensions that don't already have one.

Assuming you're using a recent version of Ruins (if not, get it!), the file you _should_ be changing is something like **world/ruins.txt**, though the "world" part may be different if you're playing single player or specified a custom **level-name** in **server.properties**. By setting **enableStick=false** there, you'll disable the Ruins stick tool...but only in the overworld. You'll also have to edit the ruins.txt files in all the world/DIMxxx folders for other dimensions to disable it there. Or, if you haven't made any per-dimension changes to Ruins configuration (and I'm guessing you haven't), it might be easier to simply delete the ruins.txt files in the world folder and all its DIMxxx subfolders, edit the one in config, and let Ruins automatically copy it to all the dimensions when the server is restarted.

**Comment by Insane96** [comment]
> you need to know all the dimensions have their own copies of ruins.txt

I was missing that. Thanks
