### ISSUE TITLE
Can't add custom loot tables to Chests in Battle Towers

### ISSUE THREAD

**Issue by FatalBlade** [AtomicStryker/atomicstrykers-minecraft-mods#206]
I've tried a few different configurations for the config file to try and get one of my custom loot tables to get rolled.
S:"Floor 1"=LootTable:thaumcraft/chests/loot_bags:5
S:"Floor 1"=ChestGenHook:chests/loot_bags:5
S:"Floor 1"=ChestGenHook:thaumcraft:chests/loot_bags:5
S:"Floor 1"=ChestGenHook:thaumcraft/chests/loot_bags:5

I have confirmed that the table is created properly and properly placed with the following

/setblock ~ ~1 ~ minecraft:chest 0 false {LootTable:"thaumcraft:chests/loot_bags"}

This will spawn a chest with the appropriate loot.

**Comment by AtomicStryker** [comment]
I dunno. Maybe instead of

LootTable loottable = world.getLootTableManager().getLootTableFromLocation(new ResourceLocation(split[1]));

it should be

LootTableManager loottablemanager = new LootTableManager((File)null);
LootTable loottable = loottablemanager.getLootTableFromLocation(new ResourceLocation(split[1]));

But someone would have to test that

**Comment by Peavii** [comment]
Can I bump this? I'm working on a modpack and I can't for the life of me get my custom loot table ('battletowerloot.json'(which is JSON validated & I've made plenty loot tables before)) to work with the battle towers using the 'Additional Loot Tables' or 'Additions' mod.

Is there a way to make the mod to use local loot tables rather than referencing vanilla's loot tables?
