### ISSUE TITLE
Staler Creepers needs to be marked 1.12.2 compatible

### ISSUE THREAD

**Issue by ghost** [AtomicStryker/atomicstrykers-minecraft-mods#219]
When searching with the Twitch client (*sob*) the mod won't show up because it's been marked for 1.12, not 1.12.2.

**Comment by AtomicStryker** [comment]
That's probably because i use a script to upload my files to curse, which means they are only flagged for the version they were uploaded for. That mod did not need a single update since 1.12 release, which means there never was an upload flagged higher.

I've flagged the latest file for 1.12, 1.12.1 and 1.12.2

**Comment by ghost** [comment]
Thank you.
