### ISSUE TITLE
Some Ruin Mod Biome Folders will not work.

### ISSUE THREAD

**Issue by CaptainStalfoss** [AtomicStryker/atomicstrykers-minecraft-mods#265]
Certain biome folders will not spawn ruins.

Version:
Ruin mod 1.12.2, (latest version on the site) 17.3.
(BOP also uses the latest 1.12.2 version.)

(I will use the BOP Biome Pasture for this example, but Other biomes such as tundra are also broken.)
![PNG - Copy](https://user-images.githubusercontent.com/38992378/59789920-16ce1180-92cf-11e9-9218-001244bf33a1.png)
As you can see here, I made a beacon ruin and set it to a super high spawn rate.
When placed in Generic, it spawns fine, even in the Pasture biome.
But, when I place the ruin in the pasture folder, it will not spawn at all.

Not all BOP biomes are broken, half of them work just fine.
Haven't tested other Mod biomes yet, but I would keep an eye on that as well.

**Comment by QuarterAnimal** [comment]
I'm not able to duplicate this problem, myself. My pasture-only ruins are spawning as expected. Check your **ruins.txt** config file and make sure it contains the line **specific_pasture=75** (or some other number greater than 0). If it's missing, that's a simple explanation for what you're seeing (maybe you're using an old config file?); if no biome-specific spawn probability is specified for a particular biome, it defaults to 0%. Either add that line, or--better still--delete the file and let Ruins recreate it and fill in all the biomes.

If you _do_ see that line in your **ruins.txt** file, something else is going on. We'd need a copy of your **ruins.txt** and template files to analyze the issue further, though, since I'm not seeing it.

**Comment by CaptainStalfoss** [comment]
Yep, Seams to have been a Faulty **ruins.txt** file.
I replaced it, and Now they spawn in those biomes, Thanks.
