### ISSUE TITLE
[Ruins][1.12.2] issues with ruins and OTG (open terrain generation)

### ISSUE THREAD

**Issue by mensreaMC** [AtomicStryker/atomicstrykers-minecraft-mods#269]
Running latest version of ruins and OTG. Running forge version 14.23.5.2838. 

It seems there's some kind of error when you run both OTG and ruins at the same time. Grass and trees are both appearing in ruins and sometimes hovering over them as well. The grass breaks on random tick updates but it's not ideal. Also, there's a lot of strange spots where it looks like a ruin tried to spawn but didn't and then just removed all the grass in the spot. Screenshots attached. There is no error log for this.

Bald spots:
![2019-07-03_21 45 21](https://user-images.githubusercontent.com/1071401/60634153-f5474c80-9ddb-11e9-9f53-47f64eb2d88f.png)

Grass:
![2019-07-03_21 45 49](https://user-images.githubusercontent.com/1071401/60634155-f7111000-9ddb-11e9-960d-0708f2937f81.png)

Trees:
![2019-07-03_21 49 08](https://user-images.githubusercontent.com/1071401/60634293-71419480-9ddc-11e9-81c1-e32de6d6970f.png)

**Comment by AtomicStryker** [comment]
A glance at their github sourcecode shows OTG hooks into minecraft much deeper than Ruins does - apparently they outright replace WorldProviders with their own variants. I am a bit surprised Ruins still works with that, honestly.

As for the problem - looks like a timing issue on generation. I suspect it would require conscious effort to make these two mods play nice together. [Don't want to invest the time for that]

**Comment by mensreaMC** [comment]
Could issues with OTG also cause ruins to spawn on top of each other regardless of settings? I see a lot of ruins that spawn either right next to each other or actually clip into each other.
![spawning together](https://user-images.githubusercontent.com/1071401/65213343-cf912180-da73-11e9-89a6-58391d73d1ae.png)
![spawning together2](https://user-images.githubusercontent.com/1071401/65213351-d324a880-da73-11e9-83fd-8ada9d9e020d.png)

**Comment by AtomicStryker** [comment]
Short answer: Yes. The mods are obviously incompatible.

**Comment by PG85** [comment]
Hey guys, thanks for looking at this. The WorldProvider is replaced to allow for dimension-specific features. OTGWorldprovider does inherit from WorldProvider though and where possible calls the base methods, which may explain why this does work partially. What's going on here I'm not exactly sure of, would need to know which resources belong to which mod, and which resources are spawned first. It does indeed look like a problem with the spawn order, or some resources using only base terrain data to determine spawn location/eligibility, instead of looking at the currently spawned blocks (which would include the ruins that have just been spawned). @AtomicStryker is right, this will need more investigation and potentially mod-specific code, which any mod author should try to avoid. @mensreaMC, If you can do a bit more digging on this and provide more information, test with/without resources to figure out which mod is spawning what when, and also test without FromImageMode (not sure if you're using it), then that may give us enough information to make it worth taking a closer look. Feel free to close the issue here and re-open it on the OTG git if that's more appropriate.

**Comment by AtomicStryker** [comment]
Thanks for popping in. As i said, i won't be doing anything about it. If someone else wants to fix and pull request it, that would be fine.
