### ISSUE TITLE
[1.14.4.2] Pet Bats crash on server

### ISSUE THREAD

**Issue by kreezxil** [AtomicStryker/atomicstrykers-minecraft-mods#301]
## Dedicated Server Crash Report:
http://paste.ubuntu.com/p/Jc3hs2ZMqv/
## latest.log:
http://paste.ubuntu.com/p/6K6zSSWHyy/
## debug.log:
http://paste.ubuntu.com/p/VtVXB75zNy/

Happened when player was naming their pet bat.

**Comment by slowiu06** [comment]
There is also a problem with bat movements, they often stucks on leaves and other blocks. They returns to hand every time I'm moving further (more often when I'm using speed buff). I think the flute and bat should be one item, I'm having problems with flute duplication occasionally, sometimes I've got flute and a bat at the same time.

In my mind this mod looks like this:
One item, RMB to realase and catch a bat, shift+RMB for stats (or vice-versa). Renaming by tag, custom name: bat. Faster movements of bats. A bit improved AI. On closer distances it should teleport to us instead of changing into item. Config file to change per-level damage/hp/speed? If a bat dies he goes back to item, we need to craft it with pumpkin cake to restore its health. Configurable limit of summoned bats.

**Comment by AtomicStryker** [comment]
Incompatible forge version, i think. There was breaking changes between 28.0.55, which Pet Bats was last built on, and your 28.1.60. Another mod of mine had similar issues ... i will recompile it for the current 28.1.61

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d45f747bbfa7b53a1fcfe39cec8623d46f9b7009

This should help your problem. Version 1.14.4.3 is on curse.


@slowiu06 
Don't piggyback on unrelated issues, please. If you think the mod could be made better, by all means submit a pull request with the improved code, i will gladly consider it.

**Comment by kreezxil** [comment]
thanks for quick update. I'll be updating the pack shortly.
