### ISSUE TITLE
Ruins do not spawn in Terraforged world type

### ISSUE THREAD

**Issue by marcusbeckerman** [AtomicStryker/atomicstrykers-minecraft-mods#350]
Using the Terraforged mod and generating a Terraforged world type, ruins do not spawn naturally. It works just fine in a default world, the nether, and the end but not in Terraforged.

**Comment by QuarterAnimal** [comment]
Ruins hooks into default vanilla chunk decoration--namely, **ChunkGenerator.decorate()**--while TerraForged overrides it entirely. It is safe to use both mods together, but Ruins structures cannot appear in TerraForged dimensions; e.g., the overworld.

This is always a potential issue whenever using multiple custom chunk generation mods in general, not just these two, and there's no practical way to resolve it. Ruins could sink its coremod hook into a different location in the code, but that just moves the issue rather than solves it and is bound to run afoul of other mods in short order. It'd certainly be possible to create a compatibility module or bridge mod specific to Ruins and TerraForged, but that sort of thing is fragile, difficult to maintain, and probably of limited utility.

If Forge were to add a chunk decoration event, it might help in this case, though I suspect that's not going to happen. An established generic scheme for custom decoration already exists, obviating the need for such an event. For better or worse, Ruins doesn't use it. Maybe it should, but that would be a radical redesign, essentially making it an entirely different mod, unable to support many of its current features.

For the time being at least, I think we just have to live with the incompatibility, unless AtomicStryker is considering a complete overhaul of Ruins in the near future.

**Comment by QuarterAnimal** [comment]
As of version 1.15.2.1, Ruins works with TerraForged.

**Comment by Sanysvo** [comment]
Its not work( i am download last ver. of Ruins and Terra and not have any structure in my terra world

**Comment by QuarterAnimal** [comment]
I just downloaded the latest versions of Forge, Ruins, and TerraForged, started up a fresh new world without making any config changes from the defaults, and I'm seeing Ruins on a TerraForged landscape. I did the same for a dedicated server installation and got the same results. Clearly the two mods _do_ work together.

What other mods are you using?
