### ISSUE TITLE
Ruins 1.12.2 Causing Cascading Worldgen lag

### ISSUE THREAD

**Issue by Zalnor** [AtomicStryker/atomicstrykers-minecraft-mods#397]
The 1.12.2 version of the Ruins mod linked bellow causes cascading worldgen lag, by itself it wouldn't be that bad but in any sizeable modpack it adds on quite a bit of cascading worldgen lag. I have also included a link explaing exactly what that is and how to go about fixing it. Example setting and offset or flags when structures are spawned partially in a chunk and when adjesent chunks load it reads it and finishes generating the structure.

https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/

https://www.curseforge.com/minecraft/mc-mods/ruins-structure-spawning-system/files/2721268

**Comment by AtomicStryker** [comment]
It can't be "fixed" without either restricting templates to fit inside a chunk, and only ever spawning them centered in a chunk or somehow running template spawning far behind the "frontier" of worldgen so that templates never go past the already generated world. Causing more worldgen to check for and fit templates is an acceptable tradeoff, and it was forges decision to make a big error logging fuss about it. They were tired of people complaining to them about performance, i guess.

The problem is much bigger in 1.16+ because access to chunks that aren't finished generating is forbidden altogether. Thats why there is no Ruins for these versions yet. I don't know if and how i will fix this.

EDIT: Well there is also the approach to plug into the vanilla structures somehow. I might have a look in my next vacation.

**Comment by Zalnor** [comment]
Have you looked into setting a offset or making it bigger if you already have one? and if you read the reddit link I posted it is indeed an issue with mods generation and should be fixable.

**Comment by AtomicStryker** [comment]
You are welcome to submit a pull request fixing the issue, i myself do not support 1.12 anymore.
