### ISSUE TITLE
DynamicLights 1.19.2 Torch Bug

### ISSUE THREAD

**Issue by RDP8** [AtomicStryker/atomicstrykers-minecraft-mods#460]
Hi, torches don't stack for whatever reason; torches that are un-used and placed in the off-hand for a certain period of time or taken out of off-hand don't stack with other torches, separating the torches that can emit light offhand, and some that cannot, can the torches just emit light permanently from offhand instead of them being separated?

**Comment by AtomicStryker** [comment]
Ah, i dont think Dynamic Lights is the cause of whatever you are experiencing. There is zero interaction with ItemStacks other than checking if the player has *configured light item* in hand. Certainly nothing that could affect stackability.

Can you reproduce this with only Dynamic Lights mod? If you can, can you produce a savegame where the bug is present?

**Comment by RDP8** [comment]
Yeah idk what it is its probably some other mod sorry for wasting your time.
