### ISSUE TITLE
[1.19.2] Ninja can cause a mob to teleport underground and suffocate

### ISSUE THREAD

**Issue by Maltshakes** [AtomicStryker/atomicstrykers-minecraft-mods#461]
I attacked a ninja mob and after a few hits, it managed to teleport itself underground and started to suffocate. I went into spectator mode to find where it had gone.

Mod version 1.19.2.2

![image](https://user-images.githubusercontent.com/76584081/205995426-1828bfb1-a498-43cb-ac4e-70f111dfa27f.png)

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ad4c83b8b926cc1ad11c4cada7e06d7c36071539

I have reworked the Ninja/Ender teleportation code and this should hopefully no longer happen. Infernal Mobs 1.19.2.3  is pushed to curse

**Comment by Coraline774477** [comment]
Thanks for fixing the Ender/Ninja abilities since those abilities got annoying every time I attacked one of the infernal mobs that had Ender or Ninja ability and they would literally teleport themselves into blocks and suffocate themselves to death and the worst part was that whatever they would drop on death of suffocation damage would be destroyed due to the blocks they got themselves into...

Also this issue isn't just in 1.19.2, it's in 1.18.2, 1.16.5 and older BUT you don't have to update the 1.16.5 and prier versions except for 1.18.2.
Since I still have two 1.18.2 worlds BUT only one of them has Infernal Mobs 1.18.2 which this issue is present in that version.

**Comment by AtomicStryker** [comment]
OK i wanted to try cherry picking and merging between branches anyway .. so there you go, the creative and teleport bugfixes for 1.19 should be backported to 1.18 now. I have pushed a new version to curse too.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/ead973bb2f9fa84eb2c90c6d65e901628a62b4f6
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/930ba8ebd82ce09b45baccac1defdde714d15406
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/9e1fbdcca6a71077a2df1bbfd2d9d11a6f2b36b0

**Comment by Coraline774477** [comment]
Thanks again and keep up the great work, hope to see Infernal Mobs in 1.19.3 soon!

But my first 1.19.3 world may or may not have Infernal Mobs in it since it's going to be like my 1.19.2 semi-modded vanilla world that has mostly QoL mods like; 
mini & world map/mimi with world map mods (Xaero's minimap mod & world map mod)(Journey Map)
*Modern UI
*RPG-HUD
*Axes Are Weapons
*Merge Enchantments, etc.

Also cause there's not gonna be alot of mods that I play with for that version yet since 1.19.3 is still only a couple days old.
*(When they're ported to 1.19.3)

**Comment by AtomicStryker** [comment]
I did the 1.19.3 ports today, enjoy.
This issue should be fixed and so i close it
