### ISSUE TITLE
large lag spikes on entering dimensional door dimension

### ISSUE THREAD

**Issue by Moonyol** [AtomicStryker/atomicstrykers-minecraft-mods#483]
![image](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/92951072/093dd565-6f0f-4d93-a25c-f2557ed28427)

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/92951072/da46caca-221d-4ffb-a2e8-e30dd7132a5d

**Comment by AtomicStryker** [comment]
No clue. You don't even have any light on you. Sorry, but i dont support such old versions anymore.

**Comment by xJon** [comment]
Just for reference, these are the results from a profiler:
![image](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/8945347/63d2ceb6-08f9-4f2c-ae0a-346bea83a15c)

**Comment by AtomicStryker** [comment]
hackRenderGlobalConcurrently is a very expensive action that is meant to run one single time when you change dimensions. Clearly it's running again and again in your case.

But this is after the global disabler button check - so just use the turn off button while in that dimension.

**Comment by AtomicStryker** [comment]
If you want to tinker with this by yourself, do not let me stop you:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/tree/1.12.2/DynamicLights

If you are very lucky, "gradlew.bat build" will still work or require minimal googling and fixing.
If you are unlucky, the relevant resources wont be online anymore.

The problem is most likely this line:
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/blob/1.12.2/DynamicLights/src/main/java/atomicstryker/dynamiclights/client/DynamicLights.java#L193

Variable "world" will either be alternating between multiple dimensions or there will be something strange about it.

**Comment by xJon** [comment]
@AtomicStryker Thank you for the hint! Will further look into this.

**Comment by xJon** [comment]
Without any code changes, adding Dimensional Doors' dimension IDs to `bannedDimensionIDs` seems to be a valid workaround:
```
    I:bannedDimensionIDs <
        -1
        684
        685
        686
        687
        688
     >
```
Interestingly this is pre-populated with `-1` for the Nether, I wonder why.

But the best solution appears to be adding [Hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus), which has code changes specifically for Dynamic Lights and it resolves this issue completely without requiring any configuration changes.

**Comment by AtomicStryker** [comment]
So a Bad interaction probably. Glad you resolved it for yourself
