### ISSUE TITLE
Multi Mine breaking state bug if drag click from another block.

### ISSUE THREAD

**Issue by FELITH** [AtomicStryker/atomicstrykers-minecraft-mods#495]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/19184069/9d34ce53-db9c-493c-951a-e5cb9afe62b6

multimine-1.20.1.2
forge 47.2.0

**Comment by AtomicStryker** [comment]
I can't reproduce this with 1.20.1.2 and 47.2.0 in my dev env. Are you doing something specific?

I started mining a tree block, shifted blocks while mining, stopped, then started again. I dont get any strange behaviour like you.

You can also go into multimine.cfg and change debugMode to true. Now your logfile will contain all the MultiMine events and telegrams

If you can reproduce the bug within 3 seconds or so and give me the logfile for that timeframe, i could have a look there

**Comment by FELITH** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/19184069/8cfd25d7-5051-4832-acf8-3d82c5ebe2f9

[latest.log](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/13539199/latest.log)

sorry for taking a while to respond. I've also removed all mods except for Multi Mine, but it's still happening.
Let me know if you need more info on this.

**Comment by AtomicStryker** [comment]
Thanks, i think i figured out what the issue was, but since i cant reproduce it, please see if this fixes it for you:
[multimine-1.20.1.3.zip](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/files/13540406/multimine-1.20.1.3.zip)
Rename the ending to .jar and replace your multi mine with it


For the record:
Progress tracking was not properly reset when switching blocks
You mined one block to a high progression, then another to a low progression, and Multi Mine did not deem it necessary to store the lower progression of the second block as the "last known" progression was higher

**Comment by FELITH** [comment]
The issue is gone with the new version you provided! Thank you for being so quick to fix it!

**Comment by AtomicStryker** [comment]
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/d3a50b2fb7017dc02183d673200d42d85f8cc2a1
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/4e1f569fc3e97a5dfee584017c3f5775fa1898ff

Fixed it in both the 1.20 branches and pushed new versions to curse. Case closed
