### ISSUE TITLE
Stalker creepers' unexpected behavior with enhanced AI and Overhaul Creepers mods

### ISSUE THREAD

**Issue by AikaBack** [AtomicStryker/atomicstrykers-minecraft-mods#497]
so stalker creepers makes creepers from mod overhaul creepers explode when they shouldn't. For example snowy creeper from that mod is neutral towards player, but is aggresive towards strays, so he attacks them. But with this mod instead of attacking them he explodes them, so it makes explosions unctontrollable as they just explode everytime seeing strays in winter biomes.

Without stalker creepers, snowy creepers attack strays and dont explode, as intended.

Another bug is that with Enhanced AI mod, creepers still explode behin players. Removing enhanced AI restores stalker creepers behavior.

minecraft version 1.20.1-forge-47.2.20
stalkercreepers-1.20.1.1.jar
creeperoverhaul-3.0.1-forge.jar
EnhancedAI-2.2.1-mc1.20.1.jar
![image](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/assets/42915767/f415ae4f-8635-403d-a0d9-c90a763fa248)

Would appreciate if you helped solving these problems!

**Comment by AtomicStryker** [comment]
Stalker Creepers replaces the default/vanilla piece of "AI"/behaviour script code that governs when a Creeper explodes. If a mod uses that same piece, maybe for their modded creepers, and does more changes on top of that, there is probably unintended interactions and bugs.

Sorry to say the only way to fix this is from the modded creepers side - they either have to use independent copies of the default explosion script which my mod wont mod, or otherwise establish compatibility.

While i could make sure my mod only works on vanilla creepers, i dont want to do that.
