### ISSUE TITLE
Cannot read field "f_91074_" because "atomicstryker.infernalmobs.client.InfernalMobsClient.mc" is null

### ISSUE THREAD

**Issue by NancalaStarry** [AtomicStryker/atomicstrykers-minecraft-mods#510]
Crashreport
[Forge 1.20.1 - mclo.gs](https://mclo.gs/7U8F5T6)
debug
[Forge 1.20.1 - mclo.gs](https://mclo.gs/E2eP1zD)
latest.log
[Forge 1.20.1  - mclo.gs](https://mclo.gs/6WdZsSf)

I found "Cannot read field "f_91074_" because "atomicstryker.infernalmobs.client.InfernalMobsClient.mc" is null" in latest.log and I think that should link to this mod.

**Comment by AtomicStryker** [comment]
[net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Client

java.lang.NullPointerException: Cannot read field "f_91074_" because "atomicstryker.infernalmobs.client.InfernalMobsClient.mc" is null
at atomicstryker.infernalmobs.client.InfernalMobsClient.onEntityJoinedWorld(InfernalMobsClient.java:36) 

Aye, this is the the relevant message.
So somehow you have EntityJoinLevelEvent before ClientPlayerNetworkEvent.LoggingIn triggered
Using some SpongeForge amalgamation...

Well, let me just add a late init if this happens for you

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/e810b3bd173292120528c9fc2f5fe2ed78013e01

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/5b2355495b496da13ade888a1305af054332f9f9

new versions for 1.20.1 and 1.21 are pushed, thanks for the report.

**Comment by NancalaStarry** [comment]
Ok. Thank you very much! :>
