### ISSUE TITLE
[NeoForge1.21][Loading Crash][LivingHurtEvent]

### ISSUE THREAD

**Issue by ootwclyhe** [AtomicStryker/atomicstrykers-minecraft-mods#511]
- Infernal Mobs (infernalmobs) has failed to load correctly
          java.lang.NoClassDefFoundError: net/neoforged/neoforge/event/entity/living/LivingHurtEvent

i really not found this event in the neoforge jarfile, how is that

Minecraft Version: 1.21
NeoForge: 21.0.40-beta
Mod Version: 1.21.1NF

**Comment by AtomicStryker** [comment]
It's because they changed neoforge just 3 days ago, breaking compatibility: https://github.com/neoforged/NeoForge/commit/003f3e45fa0be5f546fe30e235b91dd487a2279e

Its LivingDamageEvent now?

Oddly enough, when i try to compile against 21.0.40-beta, it still is LivingHurtEvent for me ... Use an older NeoForge for now, i will do an updated build later

**Comment by ootwclyhe** [comment]
LivingDamageEvent ‘s subclasses is on working, thank you for your help

**Comment by AtomicStryker** [comment]
You made your own build?

**Comment by Periam** [comment]
Was this solve in a new build? since the latest build that I have infernalmobs-1.21.1NF.jar, the issue is still present.

**Comment by AtomicStryker** [comment]
I have now built and released a new version with the released neoforge change.

https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/commit/cce860fe17152a35cb064511f4961392abe8a883
