### ISSUE TITLE
Dynamic Lights 1.20.1-2  When an item gets damaged it stops emmiting light

### ISSUE THREAD

**Issue by felivans** [AtomicStryker/atomicstrykers-minecraft-mods#524]
**Versioning**
Dynamic Lights 1.20.1-2 / Forge 

**What did you do**
Custom config item (a shield from spartan's shields) takes damage from any source, any amount.

**Expected behavior**
Dynamic Light is no longer emitted when holding or equipping the damaged item on the offhand or main hand

**Screenshots/Video**
n/a

**Comment by AtomicStryker** [comment]
If your item NBT changes because of damage and "breaks" the Dynamic Lights mapping, you can either add every single possible NBT string to the config, or use this:

1.20.1.1
- you can now configure itemstacks to ignore nbt tag equality, to shine light from items that could be
  enchanted or damaged. example: {anyNbtMatch:true,lightLevel:14s,nameId:\"minecraft:flint_and_steel\"}
  the important part is adding anyNbtMatch:true to the tag list

**Comment by felivans** [comment]
Thank you very much! In case anyone is having the same problem and stumbles with this post, for 1.20.1-2 the specific syntax is:
`,
    "{anyNbtMatch:true,lightLevel:14s,nameId:\"minecraft:flint_and_steel\"}",`
