### ISSUE TITLE
Ruins and Modern Ruins Pack causing incredible lag.

### ISSUE THREAD

**Issue by CafDad** [AtomicStryker/atomicstrykers-minecraft-mods#526]
**Versioning**
Minecraft 1.12.2, Modern Ruins pack (which uses the exact same base code as the Ruins mod)

**Problem**
On our server we have multiple worlds using both galacticraft and simple dimensions to generate several different environments for the ruins mod to generate structures. We unpacked the modern ruins pack and your ruins mod and they use the exact same base code they just added different structures. Since they do not any an issues page or anything of the sort I came here hoping for any bit of insight.

Our server is undergoing extremely massive amounts of lag, leaving us at a solid 4 ticks per second, networking issues, and our server temps burning up. After analyzing several heap dumps, profiler reports, and a few other methods, they all pinpoint to the generation caused by the ruins mod. The problem is that the structure list has grown to 41,000 entries and it seems as though the mod wants to regenerate the structures over and over again as well as attempting to generate new ones. Obviously this is a huge problem because 41k entries is taking up just about all of our space. If this was a problem stemming away from the ruins base code and something that the modern ruins pack used please forgive me but we are out of options. Any help with this issue would be greatly appreciated. For any sort of analyzing purposes the mod pack is _**Secrets of Avalon (AunisCraft 2.0)**_

**Comment by AtomicStryker** [comment]
Hey, Ruins was never designed to run on gigantic commercial servers. You could fix it by deleting the world and creating a new one, removing Ruins, or paying someone (not me) to mod Ruins 1.12.2 into a more scalable variation.

I can provide you with some ideas how it could be done:
- Instead of keeping track of chunks Ruins has run on, just set a block in each chunk such as [chunkX, bottomCoordinate, chunkZ] to a specific block so Ruins knows it has visited that chunk before
- The list of existing Ruins should be kept in a proper database rather than a gigantic textfile

I no longer support 1.12 in any way.
